/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AirbndServer } from "./AirbndServer";
import { AirbndServerCountArgs } from "./AirbndServerCountArgs";
import { AirbndServerFindManyArgs } from "./AirbndServerFindManyArgs";
import { AirbndServerFindUniqueArgs } from "./AirbndServerFindUniqueArgs";
import { DeleteAirbndServerArgs } from "./DeleteAirbndServerArgs";
import { AirbndServerService } from "../airbndServer.service";
@graphql.Resolver(() => AirbndServer)
export class AirbndServerResolverBase {
  constructor(protected readonly service: AirbndServerService) {}

  async _airbndServersMeta(
    @graphql.Args() args: AirbndServerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AirbndServer])
  async airbndServers(
    @graphql.Args() args: AirbndServerFindManyArgs
  ): Promise<AirbndServer[]> {
    return this.service.airbndServers(args);
  }

  @graphql.Query(() => AirbndServer, { nullable: true })
  async airbndServer(
    @graphql.Args() args: AirbndServerFindUniqueArgs
  ): Promise<AirbndServer | null> {
    const result = await this.service.airbndServer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AirbndServer)
  async deleteAirbndServer(
    @graphql.Args() args: DeleteAirbndServerArgs
  ): Promise<AirbndServer | null> {
    try {
      return await this.service.deleteAirbndServer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
